# Copyright 2023-present, Argilla, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from typing import Any, Dict, List

from distilabel.llms import vLLM
from distilabel.steps.tasks.craft.generator import CraftGenerator, TaskType

os.environ.get("HF_TOKEN")

llm = vLLM(
    model="mistralai/Mistral-7B-Instruct-v0.2",
    chat_template=None,
    extra_kwargs={"max_model_len": 16384},
)
llm.generation_kwargs = {
    "max_new_tokens": 1280,
    "temperature": 0.7,
    "top_p": 0.90,
    "top_k": 40,
}
corpus: List[Dict[str, Any]] = [
    {
        "text": "Using Applescript to make selections from dropdown menu and Apply I'm trying to write an Applescript that will open a webpage, change the selection in 2 dropdown menus and then click on a button to Apply the changes.\nI've extracted the IDs for the 2 dropdown menus and the button using Inspect Elements on the webpage but when I try and set the values in the Dropdown menu I get a 'missing value' error.\n\nI'm trying to set 'Daylight Saving:' (DaylightSaving1_ddlDaylightSaving) to be '1 hour' (Value 2) and 'Max Graph Size' (DaysPerGraph1_ddlDaysPerGraph) to be '1 day' (Value 1), then click the Apply button (btnModsApply)\n\nWhat have I done wrong in the script?\n\ntell application \"Safari\"\n    tell window 1\n        set current tab to (make new tab with properties {URL:\"http://www.ukho.gov.uk/easytide/easytide/ShowPrediction.aspx?PortID=0036&amp;PredictionLength=7\"})\n    end tell\ndelay 0.1\n    tell document 1\n        do JavaScript \"document.getElementById('DaylightSaving1_ddlDaylightSaving').value=2;\"\n        do JavaScript \"document.getElementById('DaysPerGraph1_ddlDaysPerGraph').value=1;\"\n        do JavaScript \"document.getElementById('btnModsApply').submit()\"\n    end tell\nend tell\n\nYou can use Automator instead of debugging javascript if you prefer that option.\n\nIn Automator.app you can set it up to open a new safari tab and then you can use the record feature (red button in the toolbar) to change the dropdown menu and press the button."
    }
]
craftgen = CraftGenerator(corpus=corpus, llm=llm, task=TaskType.RECIPEGEN, num_shots=3)
craftgen.load()
inputs: List[Dict[str, Any]] = [
    {
        "few_shots": [
            {
                "Text": "Bananarama Bread | High Protein Banana Bread\nWishing you a delightful Sunday, dear community,\nYou know the drill: Sunday equals cake day, and especially on warm summer days like today, there's nothing better than relaxing on the balcony with a tasty piece of cake and a refreshing drink. Agreed?\nIn celebration of the new products hitting the shelves, I've crafted a recipe for you that highlights the deliciousness of the new Chunky Flavor \"Bananarama.\"\nI guarantee you, this Bananarama bread is incredible!\nIt's incredibly tasty and completely sugar-free. To take it up a notch, I've added sugar-free chocolate drops that make the overall experience even better.\nWith my latest creation, the delicious Bananarama bread, another gem joins the array of fruit bread recipes on the blog. Some of you might be familiar with my zucchini and banana bread marble cake, blueberry carrot bread, or your beloved apple bread, a hit with the little ones. However, this recipe has truly captured my heart.\nI highly recommend giving this delightful treat a try, my friends. I promise you, the whole family will fall in love with my Bananarama bread!\n\nAlright, let's whip up this Bananarama Bread magic!\nPreheat your oven to a toasty 180\u00b0 fan and get your hands on an 18 cm loaf tin.\nNow, let's dive into the mix! Combine the spelt flour, light peanut cream, egg, half a mashed banana (save the other half for later topping), baking powder, and a pinch of salt. Mix it up until it's a delightful, creamy batter.\nTime to get chunky! Toss in 10g of chocolate chips and save the rest for that delicious topping. Splash in a good dose of liquid to keep things smooth. Split the batter between two bowls.\nHere's where the protein party begins! Add the Protein powder and Flavor drops to each bowl. For the chocolate batter, introduce the baking cocoa and maybe a smidge more liquid to keep that dark creamy goodness.\nNow, let's get artsy! Spoon the alternating batters into the loaf tin. To finish off, slice the remaining banana in half and press it gently into the surface, sprinkling those leftover chocolate drops like confetti.\nInto the oven it goes! Bake for around 35-40 minutes. Around the 25-minute mark, be a good baking babysitter and cover it up with aluminum foil if the surface is getting too dark.\nTip: Give it a gentle press around the 35-minute mark to check if it's ready. Now, let the Bananarama Bread adventure begin! Enjoy!",
                "Instruction": "I want to bake a high-protein version of banana bread. Which ingredients do I need and in which order do I prepare them correctly?",
                "Output": 'Ingredients:\n* 20g Protein powder "Vanilla Ice Cream"\n* 4g Flavor drops "Bananarama"\n* 20g Protein powder "Chocolate Brownie"\n* 4g Chunky Flavor "Stracciatella"\n* 10g Baking Cocoa\n* 30g Spelt Flour\n* 20g Light Peanut Cream\n* 1 Egg\n* 1 Banana (half mashed, half sliced for topping)\n* 5g Baking Powder\n* 1 Pinch of Salt\n* 15g Sugar-free Dark Chocolate Drops\n\nSteps:\n1. Preheat the Oven:\nPreheat your oven to 180\u00b0C with a fan and prepare an 18cm loaf tin.\n\n2. Prepare the Base:\nIn a mixing bowl, combine spelt flour, light peanut cream, egg, half of the mashed banana (keep the other half for topping), baking powder, and a pinch of salt. Mix until you achieve a creamy batter.\n\n3. Add Chocolatey Goodness:\nToss in 10g of chocolate chips into the batter and reserve the remaining for the topping. Adjust the consistency by adding a bit of liquid, ensuring both the light and dark batters are equally creamy.\n\n4. Protein Party:\nDivide the batter into two bowls. Add Protein powder and Flavor drops to each bowl. Introduce baking cocoa to the chocolate batter, and if needed, adjust the consistency with a bit of liquid.\n\n5. Layer it Up:\nAlternately spoon both batter mixtures into the loaf tin. Top it off by pressing the remaining banana slices into the surface and sprinkling the rest of the chocolate drops.\n\n6. Bake to Perfection:\nBake for approximately 35-40 minutes. Cover with aluminum foil around the 25-minute mark if the surface is getting too dark.\n\n7. Check for Readiness:\nPerform a light pressure test around the 35-minute mark to ensure the cake is ready.',
            },
            {
                "Text": "Wiener Schnitzel\nThis recipe always works and tastes like the original from Vienna. The secret is the clarified butter. Then the Wiener Schnitzel becomes tender and crispy.\nPlace the schnitzel on top, remove any skin and pound until thin. Season with salt and pepper on both sides. Place the flour and breadcrumbs on a flat plate, break the eggs into a plate and stir with a fork.\nDredge the schnitzel one at a time in flour on both sides, then dip into the beaten eggs, making sure that no part remains dry. Finally, roll in the breadcrumbs and gently press the breadcrumbs with the back of the fork (this makes the breadcrumbs \u201csouffl\u00e9\u201d more beautifully).\nIn a large pan (or 2 medium pans) melt enough clarified butter so that the schnitzels can float easily (or heat vegetable oil with 1 - 2 tablespoons of clarified butter or butter).\nOnly add the schnitzel when the fat is so hot that it foams up and hisses when you drop a few crumbs or a small piece of butter into it.\nDepending on the thickness and type of meat, bake the schnitzel for 2 minutes (for thin veal schnitzel) to 4 minutes (for thicker pork schnitzel) until golden brown. Turn with a spatula (do not pierce!) and bake on the other side until golden brown.\nRemove the crispy schnitzels and let them drain on kitchen paper. Gently pat dry. Serve and garnish with lemon slices before serving.\nServe with parsley potatoes, rice, potato salad or mixed salad.\n\nA Wiener Schnitzel is actually the preferred dish at the Sunday lunch table of Austrian families or when visiting a Viennese pub. With the golden yellow coating, it not only looks good on the plate, but also tastes tender, juicy and crispy at the same time. It's right in the middle of real life.\nGarnished with parsley potatoes or potato salad, cranberries and a lemon wedge, the Wiener Schnitzel is a feast for the eyes. This explains why this dish has spread rapidly to all Austrian federal states. The schnitzel is known in the city, on the lake, on the mountain and in every corner of the country. Although the reputation of its predecessor was not flawless, it is the favorite dish of Austrians.\nAnyone who orders a schnitzel in Austria must know that not every schnitzel can simply be called Wiener Schnitzel. When Wiener Schnitzel is on the menu, it means a veal schnitzel that is fried in clarified butter.\nBefore breading, the meat is carefully pounded, seasoned and moistened, then coated in flour, egg and finally breadcrumbs. The breadcrumbs are not pressed down so that the breadcrumbs stir when baked, i.e. make waves. This is how this \u201cWow!\u201d I am a real Wiener Schnitzel!\u201d effect.",
                "Instruction": "How can I cook an original Wiener Schnitzel?",
                "Output": "Ingredients:\n* Veal schnitzel\n* Clarified butter\n* Salt\n* Pepper\n* Flour\n* Breadcrumbs\n* Eggs\n* Lemon slices (for garnish)\n* Parsley potatoes, rice, potato salad, or mixed salad (for serving)\n\nSteps:\n1. Prepare Schnitzel:\n* Place the veal schnitzel on a flat surface, remove any skin, and pound until thin.\n* Season both sides of the schnitzel with salt and pepper.\n\n2. Coating Process:\n* On a flat plate, spread out flour and breadcrumbs.\n* In a separate plate, break the eggs and stir with a fork.\n* Dredge the schnitzel in flour on both sides.\n* Dip the floured schnitzel into the beaten eggs, ensuring it's fully coated.\n* Finally, roll the schnitzel in breadcrumbs, gently pressing them with the back of a fork for a beautiful \"souffl\u00e9\" effect.\n\n3. Prepare Pan:\n* In a large pan (or 2 medium pans), melt enough clarified butter so that the schnitzels can float easily. Alternatively, heat vegetable oil with 1-2 tablespoons of clarified butter or regular butter.\n\n4. Frying Process:\n* Only add the schnitzel to the hot fat when it's foaming and hissing (test with a few crumbs or a small piece of butter).\n* Depending on the thickness and type of meat, fry the schnitzel for 2 to 4 minutes until golden brown.\n* Turn with a spatula (avoid piercing the schnitzel) and fry on the other side until golden brown.\n\n5. Drain and Pat Dry:\n* Remove the crispy schnitzels and let them drain on kitchen paper.\n* Gently pat them dry.\n\n6. Serve:\n* Serve the Wiener Schnitzel garnished with lemon slices.\n* Accompany with parsley potatoes, rice, potato salad, or mixed salad.\n\n7. Enjoy:\n* The golden yellow coating ensures it looks as good as it tastes\u2014tender, juicy, and crispy all at once.\n* Garnish with parsley potatoes or potato salad, cranberries, and a lemon wedge for a visually delightful experience.",
            },
            {
                "Text": "Self-made Ice Cream\nYou can also make your own ice cream without an ice cream maker. You can use regional, seasonal and organic ingredients and also make vegan ice cream. We'll show you how it's done.\nMaking your own ice cream \u2013 how does it work?\nIce is basically nothing more than a frozen liquid. To prevent it from freezing into a hard block like an ice cube, it is stirred regularly. This breaks up the ice crystals and makes the ice cream creamy. That's exactly what an ice cream maker does: it cools the ice cream mixture and constantly stirs it.\nBut you can also make ice cream yourself without an ice cream maker. That is how it goes:\nMix the ingredients according to the recipe and pour them into a freezer container.\nPlace the container in the freezer.\nCheck every now and then to see whether the mixture is starting to freeze.\nStir the ice cream mixture vigorously with a whisk or fork as soon as the first ice crystals form. Then put the ice cream cold again.\nRepeat the previous step three to four more times after half an hour.\nIf the ice cream is still too soft, leave it cold for another hour or two before eating it.\n\nIf this is too time-consuming for you but you don't want to miss out on homemade ice cream, you can of course also use an ice cream maker. Maybe it's worth buying them together with friends or neighbors and swapping them back and forth with each other.\n\nStrawberry ice cream:\n150g strawberries\n70 g fine sugar or powdered sugar\n125 ml fresh organic milk\n50 ml sweet organic cream\n2 tbsp lemon juice\nPuree the strawberries with the sugar.\nMix the fruit puree with milk and lemon juice.\nWhip the cream until stiff and mix it in too.\nMake the ice cream as described above.\nVariation: You can use any other seasonal berries instead of strawberries.\n\nChocolate ice cream:\n100 ml whole milk\n50 g fair trade chocolate (70% cocoa content)\n50 g fair trade chocolate (whole milk)\n200 g organic cream\n1 tsp powdered sugar\nWarm the milk and melt the chocolate in it.\nThen let the mixture cool down.\nBeat the cream with the powdered sugar until stiff and mix it with the chocolate milk.\nThen continue as described above.\n",
                "Instruction": "How can I make ice cream at home without an ice cream maker?",
                "Output": "Base Ingredients:\n* Fresh organic milk\n* Sweet organic cream\n* Fine sugar or powdered sugar\n\nAdd different fruits and flavors. For instance:\nStrawberry Ice Cream:\nIngredients:\n* 150g strawberries\n* 70g fine sugar or powdered sugar\n* 125ml fresh organic milk\n* 50ml sweet organic cream\n* 2 tbsp lemon juice\n\nSteps:\nBase:\n1. Prepare the Ice Cream Base:\nMix fresh organic milk, sweet organic cream, and fine sugar or powdered sugar according to your recipe.\n\n2. Freezing Process:\nPour the ice cream mixture into a freezer container.\n\n3. Freeze and Stir:\nPlace the container in the freezer.\nCheck periodically to see if the mixture is starting to freeze.\n\n4. Stirring Steps:\nVigorously stir the ice cream mixture with a whisk or fork as soon as the first ice crystals form.\nPut the container back in the freezer.\n\n5. Repeat Stirring:\nRepeat the stirring process three to four more times, with intervals of around half an hour.\n\n6. Final Freezing:\nIf the ice cream is still too soft, leave it in the freezer for another hour or two before serving.\n\n7. Enjoy Homemade Ice Cream:\nYour homemade ice cream is ready to be savored!\n\nFor strawberry ice-cream:\n1. Prepare Strawberry Puree:\nPuree the strawberries with the sugar.\n\n2. Mix Ingredients:\nCombine the fruit puree with milk and lemon juice.\n\n3. Whip and Mix:\nWhip the cream until stiff and fold it into the strawberry mixture.\n\n4. Follow Homemade Ice Cream Steps:\nProceed with the homemade ice cream process described above.\n\n5. Variation:\nFeel free to use any other seasonal berries instead of strawberries.",
            },
        ]
    },
]
res = next(craftgen.process(inputs=inputs))
print(res)
